{% set name = "pyIsEmail" %}
{% set version = "2.0.1" %}
{% set sha256 = "daf4b3fb2150a38f406b0aaba729e19fcd638a6d1c0549c25ff54c7b804618f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dnspython >=1.15.0

test:
  imports:
    - pyisemail
    - pyisemail.diagnosis
    - pyisemail.validators

about:
  home: https://github.com/michaelherold/pyIsEmail
  license: MIT
  license_file: LICENSE
  summary: Simple, robust email validation

extra:
  recipe-maintainers:
    - mrakitin
